export const sampleVehicles = [
  {
    make: 'Tesla',
    model: 'Model 3',
    logo: 'https://www.freepnglogos.com/uploads/tesla-logo-png-black-1.png',
    price: 30000,
    year: 2019,
    MPG: 50,
    fuelSpending: 0,
    type: 'Electric',
  },
  {
    make: 'Tesla',
    model: 'Model X',
    logo: 'https://www.freepnglogos.com/uploads/tesla-logo-png-black-1.png',
    price: 90000,
    year: 2016,
    MPG: 70,
    fuelSpending: 0,
    type: 'Electric',
  },
  {
    make: 'Tesla',
    model: 'Model S',
    logo: 'https://www.freepnglogos.com/uploads/tesla-logo-png-black-1.png',
    price: 80000,
    year: 2014,
    MPG: 60,
    fuelSpending: 0,
    type: 'Electric',
  },
  {
    make: 'Nissan',
    model: 'Leaf',
    logo: 'https://www.freepnglogos.com/uploads/nissan-logo-23.png',
    price: 24000,
    year: 2018,
    MPG: 35,
    fuelSpending: 800,
    type: 'Hybrid',
  },
  {
    make: 'Nissan',
    model: 'Leaf',
    logo: 'https://www.freepnglogos.com/uploads/nissan-logo-23.png',
    price: 25000,
    year: 2021,
    MPG: 35,
    fuelSpending: 800,
    type: 'Hybrid',
  },
  {
    make: 'Toyota',
    model: 'Prius',
    logo:
      'https://www.freepnglogos.com/uploads/toyota-logo-png/toyota-logos-download-image-15.png',
    price: 25000,
    year: 2019,
    MPG: 53,
    fuelSpending: 700,
    type: 'Hybrid',
  },
  {
    make: 'Toyota',
    model: 'Prius Prime',
    logo:
      'https://www.freepnglogos.com/uploads/toyota-logo-png/toyota-logos-download-image-15.png',
    price: 28000,
    year: 2021,
    MPG: 54,
    fuelSpending: 700,
    type: 'Hybrid',
  },
];
